"""
alembic/env.py

Async migration environment. Reads the database URL from
``aether.config.settings`` (not from ``alembic.ini``) so there is a
single source of truth for the connection string, consistent with
coding convention #9 ("all config via settings object. No os.getenv()
outside config.py").

NOTE: as with ``aether/database.py``, this file imports
``aether.config``, which does not exist until Step 7. Until then,
``alembic upgrade head`` cannot run — the migration files themselves
are still fully written and inspectable in the interim.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Import Base + every model module so `Base.metadata` is fully
# populated. Phase-0 migrations are hand-written (not autogenerated),
# but keeping metadata complete costs nothing and unblocks
# `alembic revision --autogenerate` for Phase-1+.
from aether.models.base import Base
from aether.models import logs, nodes, runtime, sessions  # noqa: F401
from aether.config import settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Override whatever `sqlalchemy.url` alembic.ini has (intentionally
# blank) with the real URL from Settings. Deliberately
# migration_database_url, NOT database_url — see aether/config.py and
# migration 0001's docstring: migrations need owner-level privileges
# that the app's own restricted database_url role does not have.
config.set_main_option("sqlalchemy.url", settings.migration_database_url)


def run_migrations_offline() -> None:
    """Run migrations without a live DB connection (emits SQL to stdout)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations against a live DB using an async engine."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
